### ISSUE TITLE
[CHECKLIST]: v0.10.0 bugfix plan

### ISSUE THREAD

**Issue by suvam0451** [suvam0451/dhaaga#154]
### Description

The following features and bug fixes are expected for **v0.9.1** (feedback from users)

- [x] [Setting] Quick Reaction
- [x] [Setting] Disable Remote Instance Calls
- [x] [Fix] Reaction cache should be populated on account addition (prevents crash)
- [x] [Fix] An empty reaction cache should not cause app crash in composer
- [ ] [Fix] Sometimes adding reactions gets stuck (only if initiated via clicking the reaction to view details)
- [x] [Fix] Gallery View missing for some backends
- [x] [Fix] Clicking pinned posts causes app crash

### App Version

v0.9.0

### Install Source

Play Store

**Comment by suvam0451** [comment]
Shipped.
